---
# tag::app-deployment[]
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-app
  labels:
    app: elastic-app
  annotations:
    service.binding/type: "elasticsearch"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-app
  template:
    metadata:
      labels:
        app: elastic-app
    spec:
      containers:
        - name: app
          image: quay.io/kmamgain/elastic:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 3000