apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: elastic-binding-sed
spec:
  application:
    group: apps
    name: elastic-app
    resource: deployments
    version: v1
  bindAsFiles: true
  detectBindingResources: true
  services:
    - group: ""
      kind: Secret
      name: io.servicebinding.elasticsearch-sed
      version: v1